cache:
  paths:
    - node_modules/



before_script:
  - npm install

stages:
  - test
  - build
  - build-docker

test:
  image: node:8.9.0 # change to match your node version
  stage: test
  script:
    - CI=true npm run test-ci
  rules:
    - when: never

build:
  image: node:8.9.0
  stage: build
  script:
    - CI=true npm run-script build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public/
    

build-docker:
  before_script:
    - echo "pass"
  stage: build-docker
  dependencies:
    - build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

variables:
  STAGING_NAMESPACE: app-stage
  PRODUCTION_NAMESPACE: app-prod





