cache:
  paths:
    - node_modules/

variables:
  DOCKER_HOST: tcp://localhost:2375
  priviledged: true
  gitlab-runner.runners.privileged: true


before_script:
  - npm install

stages:
  - test
  - build
  - build-docker
  - deploy

test:
  image: node:7.9.0 # change to match your node version
  stage: test
  script:
    - CI=true npm run test-ci
    
build:
  image: node:7.9.0
  stage: build
  script:
    - CI=true npm run build
    - rm -rf public
    - mv build public
    

build-docker:
  before_script:
    - echo "pass"
  image: docker:latest
  services: 
    - docker:dind
  stage: build-docker
  script:
    - docker build . -t registry.gitlab.com/bjoern_urban_5/webcv:latest
    - docker push registry.gitlab.com/bjoern_urban_5/webcv:latest

pages:
  stage: deploy
  script:
    kubectl create -f frontend-deployment.yaml
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch