plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/gitlab"
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - "master"
  - name: "development"
    prerelease: "rc"
    channel: false
