plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@saithodev/semantic-release-backmerge"
    - branches:
        - from: master
          to: development
      plugins:
        - - "@semantic-release/exec"
          - successCmd: echo 'Version in master is ${nextRelease.version}' > test.txt
              && git add test.txt
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/gitlab"
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - "master"
  - name: "development"
    prerelease: "rc"
    channel: "false"
