apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    spec:
	containers:
	- env:
	  image: 
	  imagePullPolicy: Always
	  name: frontend
	  ports: 
	  - containerPort: 80
